"""empty message

Revision ID: 61baa44ab81e
Revises: 9877a287cf7a
Create Date: 2020-02-11 22:03:18.407932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61baa44ab81e'
down_revision = '9877a287cf7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general_records', sa.Column('cargiver', sa.String(length=100), nullable=False))
    op.add_column('general_records', sa.Column('likes', sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('general_records', 'likes')
    op.drop_column('general_records', 'cargiver')
    # ### end Alembic commands ###
