"""empty message

Revision ID: 9877a287cf7a
Revises: 
Create Date: 2020-01-27 20:41:34.659836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9877a287cf7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petname', sa.String(length=80), nullable=False),
    sa.Column('dob', sa.String(length=60), nullable=False),
    sa.Column('imglink', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vet_name', sa.String(length=80), nullable=False),
    sa.Column('groomer_name', sa.String(length=80), nullable=False),
    sa.Column('vet_address', sa.String(length=120), nullable=False),
    sa.Column('groomer_address', sa.String(length=120), nullable=False),
    sa.Column('insurance_policy', sa.String(length=120), nullable=False),
    sa.Column('insurance_provider', sa.Integer(), nullable=False),
    sa.Column('petname', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('insurance_policy')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('petname', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login')
    op.drop_table('user')
    op.drop_table('general_records')
    op.drop_table('dogfile')
    # ### end Alembic commands ###
